todoapp/todo_list/urls.py
from django.urls import path, include
from todo_list import views

app_name = 'todo_list'

urlpatterns = [
    path('', views.ListTodo.as_view(), name='list'),
    path('<int:pk>', views.DetailsTodo.as_view(), name='details'),
    path('create/', views.CreateTodo.as_view(), name='createtodo'),
    path('update/<int:pk>', views.UpdateTodo.as_view(), name='updatetodo'),
    path('delete/<int:pk>', views.DeleteTodo.as_view(), name='deletetodo'),
    path('listallorone/', views.ListAllOrOne.as_view(), name="lsitallorone")
 ]

todoapp/todoapp/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from todo_list.views import Index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',Index.as_view(),name="home"),
    path(r'todolist/',include('todo_list.urls', namespace='todo_list')),
]

urlpatterns += staticfiles_urlpatterns()

todoapp/todo_list/models.py
from django.db import models

# Create your models here.
from django.urls import reverse

STATUS_CHOICE = [
    ('progress', 'progress'),
    ('completed', 'completed'),
    ('pending', 'pending'),
]


class Todos(models.Model):
    title = models.CharField(max_length=256, null=False)
    description = models.TextField(max_length=256)
    todo_date_time = models.DateTimeField()
    status = models.TextField(max_length=20, choices=STATUS_CHOICE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("todo_list:details", kwargs={'pk': self.pk})

    def get_undeleted_tasks(self):
        return Todos.objects.filter(is_deleted=False)

    def get_task(self, pk):
        return Todos.objects.first(pk=pk)

todoapp/todo_list/forms.py
from django import forms
from todo_list.models import Todos
from todoapp import settings


class TodosForm(forms.ModelForm):
    todo_date_time = forms.DateTimeField(
        input_formats=['%Y-%m-%dT%H:%M'],
        widget=forms.DateTimeInput(
            attrs={
                'type': 'datetime-local',
                'class': 'form-control'},
            format='%Y-%m-%dT%H:%M')
    )

    class Meta:
        model = Todos
        fields = ['title', 'description', 'status', 'todo_date_time']

todoapp/todo_list/views.py
from django.core import serializers

# Create your views here.
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from django.views.generic.base import View, TemplateView

from todo_list.forms import TodosForm
from todo_list.models import Todos


class Index(TemplateView):
    template_name = 'index.html'


class CreateTodo(CreateView):
    model = Todos
    form_class = TodosForm
    template_name = 'todo_create.html'
    # success_url = reverse_lazy("todo_list:list")


class ListTodo(ListView):
    model = Todos
    template_name = 'todo_listview.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tasks'] = Todos().get_undeleted_tasks()
        return context


class DetailsTodo(DetailView):
    model = Todos
    context_object_name = 'task'
    template_name = 'todo_detail.html'


class UpdateTodo(UpdateView):
    model = Todos
    form_class = TodosForm
    template_name = 'todo_create.html'


class DeleteTodo(DeleteView):
    model = Todos
    template_name = 'todo_delete.html'
    context_object_name = 'task'
    success_url = reverse_lazy("todo_list:list")

    def delete(self, request, *args, **kwargs):
        """
        Call the save method on the fetched object and then redirect to the
        success URL.
        """
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.is_deleted = True
        self.object.save()
        return HttpResponseRedirect(success_url)


class ListAllOrOne(View):
    def __init__(self):
        super().__init__()

    def get(self, requets):
        id = requets.GET.get('id', None)
        queryset = Todos.objects.all()
        fields=('title','description', 'todo_date_time','status','created_at', 'modified_at', 'is_deleted')
        if id:
            todo_one_json = serializers.serialize("json", queryset.filter(id=id), fields=fields)
            return JsonResponse({"data":todo_one_json}, content_type="application/json")
        todo_json = serializers.serialize("json", queryset, fields=fields)
        return JsonResponse({"data":todo_json}, content_type="application/json")

todoapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Abode</title>
    <!-- Latest compiled and minified CSS -->
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">

</head>
<body>

<nav class="navbar nav-fill">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'todo_list:list' %}">Todo List</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
        </li>
    </ul>
</nav>

<div class="container">
    {% block content %}

    {% endblock %}
</div>

</body>
</html>

todoapp/templates/index.html
{% extends "base.html" %}
 {% block content %}
     <div class="jumbotron">
        <h1>   Welcome to TODO List ! </h1>
        <h3>   Click Todo list to see TODO's </h3>
        <h3>   Click Admin to use TODO's Admin Interface </h3>
     </div>
 {% endblock %}

todoapp/todo_list/templates/todo_create.html
{% extends "base.html" %}
 {% block content %}
    <div class="jumbotron">
            <form method="post">
                {% csrf_token %}
                <div class="jumbotron-fluid">
                {{ form.as_p}}
                </div>
                <input type="submit" value="Submit" class="btn btn-primary">
            </form>
    </div>
 {% endblock %}

todoapp/todo_list/templates/todo_delete.html
{% extends 'base.html' %}

{% block content %}
    <div class="jumbotron">
        <h1> Do you want to delete Task ! </h1>
        <form method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete "{{ task.title }}"?</p>
            <p>
                <input type="submit" class="btn btn-danger" value="Delete">
                <a class="btn btn-success" href="{% url 'todo_list:details' pk=task.pk %}">Cancle</a>
            </p>
        </form>
    </div>

{% endblock %}

todoapp/todo_list/templates/todo_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="jumbotron">
        <h1> Welcome to Task ! - {{ task.title }}</h1>
        <div class="container">
            <h5>Description: {{ task.description }}</h5>
            <h5>Status : {{ task.status }}</h5>
            <h5>Created On: {{ task.created_at }}</h5>
            <h5>Modified On: {{ task.modified_at }}</h5>
            <h5>ETA : {{ task.todo_date_time }}</h5>
        </div>
        <div class="container">
            <p>
                <a class="btn btn-warning" href="{% url 'todo_list:updatetodo' pk=task.pk %}">Update</a>
                <a class="btn btn-outline-danger" href="{% url 'todo_list:deletetodo' pk=task.pk %}">Delete </a>
                <a class="btn btn-outline-secondary" href="{% url 'todo_list:list' %}">Todo List</a>
            </p>
        </div>
    </div>
{% endblock %}

todoapp/todo_list/templates/todo_listview.html
{% extends 'base.html' %}

{% block content %}
    <div class="jumbotron">
    <h1> Welcome to TODO List ! </h1>
    <ol>
        {% for task in tasks %}
                <li>
                    <p class="container">
                        <a href="{{ task.id }}">{{ task.title }}</a> - {{ task.status }}
                        <a class="btn btn-warning btn-sm" href="{% url "todo_list:details" pk=task.pk %}"> Update</a>
{#                        <a class="btn btn-outline-danger" href="{% url "todo_list:deletetodo"  pk=task.pk%}"> Delete</a>#}
                    </p>
                </li>
        {% empty %}
            <h3>No TODO List Add one !</h3>
            <a class="btn btn-success" href="{% url "todo_list:createtodo" %}"> Create TODO</a>
        {% endfor %}
    </ol>
    {% if tasks %}
        <a class="btn btn-success" href="{% url "todo_list:createtodo" %}"> Create TODO</a>
    {% endif %}
    </div>
{% endblock %}